### ISSUE TITLE
Rename this. to avoid Trademark infringment

### ISSUE THREAD

**Issue by usyboi** [kamaravichow/tune-catcher-android#2]
as mentioned by u/MotorolaDroidMofo

 you should rename this. Since you don't own the YouTube trademark, don't be surprised if you get cease-and-desisted. You also don't own the youtube.ly domain name which could further cause some issues for you - it's trademark infringement for one thing, and it's also simply misleading and confusing.

**Comment by kamaravichow** [comment]
I understand.
