### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by aha999** [kamaravichow/tune-catcher-android#4]
Add dark mode, which eases app's usage at night.

**Comment by kamaravichow** [comment]
Man why would you need dark mode in that? If you still want it you can always fork it.

**Comment by aha999** [comment]
Because it's really bright and users like to switch light/dark modes if they prefer one or another, especially for night owls. I have my Android system theme on dark, and if Youtube.ly would have the 'follow the system theme' option on by default, as most apps have, that would be awesome.
