### ISSUE TITLE
About page

### ISSUE THREAD

**Issue by aha999** [kamaravichow/tune-catcher-android#5]
Please add About page button in menu options that shows a description of the app, developer, link to source code...

**Comment by kamaravichow** [comment]
That doesn't matter as I'm not planning on publishing it anywhere.

**Comment by aha999** [comment]
i understand, but if for example someone uses it and wants to see the source code/wants to publish issues/ to contribute, there's no direct way to see where the project is held...
we have to manually search for it, instead of opening 'about page' and clicking the link.
